language: python
python:
  - "3.9"
install:
    - pip install -r requirements.txt
    - pip install pyyaml
    - pip install coverage
    - pip install coveralls
# command to run tests
script:
  - coverage run -m unittest discover tests && coverage report -m

branches:
  only:
    - master
after_success:
  coveralls